SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720

PLAYER_HEALTH = 50
PLAYER_CONTACT_DAMAGE_COOLDOWN_SECONDS = 0.5
PLAYER_SHOT_SPEED = 200
PLAYER_SHOT_DAMAGE = 6
PLAYER_SHOT_COOLDOWN_SECONDS = 1.30
PLAYER_SHOT_MAX_DISTANCE = 600

SHOT_RADIUS = 4

ENEMY_HEALTH = 10
ENEMY_CONTACT_DAMAGE = 10
ENEMY_SPEED = 100
ENEMY_SPAWN_RATE_SECONDS = 1.50
